name: ci

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: Swatinem/rust-cache@v2
      - run: nix-shell --run 'cargo fmt --check'
      - run: nix-shell --run 'cargo clippy --locked --all-targets -- --deny warnings'
      - run: nix-shell --run 'cargo test --locked -- --test-threads=2'

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-audit
      - run: cargo audit
